const products = [
  {
    id: '001',
    image: 'Images/1.webp',
    company: 'StyleHub',
    item_name: 'Men Cotton Printed T-Shirt',
    original_price: 999,
    current_price: 599,
    discount_percentage: 40,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.3, count: 1850 },
  },
  {
    id: '002',
    image: 'Images/2.jpg',
    company: 'DenimCo',
    item_name: 'Slim Fit Blue Jeans',
    original_price: 2199,
    current_price: 1399,
    discount_percentage: 36,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.2, count: 1320 },
  },
  {
    id: '003',
    image: 'Images/jacket4.webp',
    company: 'WinterX',
    item_name: 'Men Winter Jacket',
    original_price: 2999,
    current_price: 1699,
    discount_percentage: 38,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.5, count: 980 },
  },

  {
    id: '004',
    image: 'Images/4.webp',
    company: 'Bitya By Bhama',
    item_name: 'Bitya by Bhama Girls yellow & red printed grown Dress',
    original_price: 41900,
    current_price: 1099,
    discount_percentage: 74,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.5, count: 950},
  },

  {
    id: '005',
    image: 'Images/kurta.webp',
    company: 'EthinStyle',
    item_name: 'Women Pritned Kurti',
    original_price: 1799,
    current_price: 1099,
    discount_percentage: 39,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.4, count: 2140},
  },

  {
    id: '006',
    image: 'Images/maxi4.webp',
    company: 'GlowFashion',
    item_name: 'Women Floral Maxi Dress',
    original_price: 2499,
    current_price: 1599,
    discount_percentage: 36,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.5, count: 1680 },
  },
  {
    id: '007',
    image: 'Images/saree7.webp',
    company: 'EthniStyle',
    item_name: 'Red Silk Party Saree',
    original_price: 3999,
    current_price: 2499,
    discount_percentage: 38,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.5, count: 860 },
  },
  {
    id: '008',
    image: 'Images/14.jpg',
    company: 'GlowUp',
    item_name: 'Women Makeup Kit',
    original_price: 3499,
    current_price: 2199,
    discount_percentage: 37,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.3, count: 1250 },
  },
   
  {
    id: '009',
    image: 'Images/shoes2.png',
    company: 'UrbanStep',
    item_name: 'Men Casual Sneakers',
    original_price: 2899,
    current_price: 1799,
    discount_percentage: 38,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.3, count: 1120 },
  },

  {
    id: '010',
    image: 'Images/heel2.png',
    company: 'StyleWalk',
    item_name: 'Women High Heels Stilettos',
    original_price: 3299,
    current_price: 2099,
    discount_percentage: 36,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.4, count: 840 },
  },

  
  {
    id: '011',
    image: 'Images/slipper.png',
    company: 'ComfortWalk',
    item_name: 'Men Causual Rubber Slippers',
    original_price: 999,
    current_price: 599,
    discount_percentage: 40,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.2, count: 820 },
  },

  
  {
    id: '012',
    image: 'Images/wslip.png',
    company: 'UrbanChic',
    item_name: 'Women Stylish Flat Slippers',
    original_price: 1299,
    current_price: 799,
    discount_percentage: 38,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.3, count: 640 },
  },

   {
    id: '013',
    image: 'Images/glass.webp',
    company: 'SunX',
    item_name: 'UV Protected Sunglasses',
    original_price: 1599,
    current_price: 999,
    discount_percentage: 38,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.0, count: 540 },
  },

  {
    id: '014',
    image: 'Images/wallet.png',
    company: 'LeatherPro',
    item_name: 'Genuine Leather Wallet',
    original_price: 1299,
    current_price: 799,
    discount_percentage: 38,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.1, count: 670 },
  },
  {
    id: '015',
    image: 'Images/bottle.png',
    company: 'HydroSteel',
    item_name: 'Stainless Steel Water Bottle',
    original_price: 999,
    current_price: 599,
    discount_percentage: 40,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.6, count: 1680 },
  },
  {
    id: '016',
    image: 'Images/perfume.png',
    company: 'AromaPlus',
    item_name: 'Long Lasting Perfume',
    original_price: 1999,
    current_price: 1299,
    discount_percentage: 35,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.4, count: 880 },
  },
  {
    id: '017',
    image: 'Images/smart1.png',
    company: 'FlitLife',
    item_name: 'Smart Watch with Heart Rate',
    original_price: 4999,
    current_price: 2999,
    discount_percentage: 40,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.2, count: 1950 },
  },

  {
    id: '018',
    image: 'Images/power.png',
    company: 'chargeUp',
    item_name: '10000mAh Power Bank',
    original_price: 1999,
    current_price: 1199,
    discount_percentage: 40,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.3, count: 2200 },
  },
  {
    id: '019',
    image: 'Images/earbuds.png',
    company: 'BeatPro',
    item_name: 'True Wireless Earbuds',
    original_price: 2999,
    current_price: 1699,
    discount_percentage: 43,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.3, count: 3100 },
  },
  {
    id: '020',
    image: 'Images/lap1.png',
    company: 'TechCore',
    item_name: 'Laptop 15.6 inch i5',
    original_price: 59999,
    current_price: 49999,
    discount_percentage: 17,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.5, count: 860 },
  },
   {
    id: '021',
    image: 'Images/car1.png',
    company: 'KiddoFun',
    item_name: 'Kids Remote Control Car',
    original_price: 1999,
    current_price: 1299,
    discount_percentage: 35,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.6, count: 1850 },
  },
   {
    id: '022',
    image: 'Images/toy1.png',
    company: 'TinyJoy',
    item_name: 'Kids Doll House Play Set',
    original_price: 2499,
    current_price: 1599,
    discount_percentage: 36,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.5, count: 1420 },
  },
   {
    id: '023',
    image: 'Images/blok1.png',
    company: 'EduPlay',
    item_name: 'Kids Educational Building Blocks',
    original_price: 1499,
    current_price: 899,
    discount_percentage: 40,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.7, count: 2100 },
  },
   {
    id: '024',
    image: 'Images/teddy.png',
    company: 'CuddleBear',
    item_name: 'Kids Soft Teddy Bear Toy',
    original_price: 1299,
    current_price: 799,
    discount_percentage: 38,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.8, count: 2650 },
  },

  {
    id: '025',
    image: 'Images/kidbag.png',
    company: 'SchoolMate',
    item_name: 'Kids Cartoon School Backpack',
    original_price: 1499,
    current_price: 899,
    discount_percentage: 40,
    return_period: 14,
    delivery_data: '31 Dec 2025',
    rating: { stars: 4.6, count: 1280 },
  }
  
];
