const products = [
  {
    id: '001',
    image: 'Images/1.webp',
    company: 'StyleHub',
    item_name: 'Men Cotton Printed T-Shirt',
    original_price: 999,
    current_price: 599,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.3, count: 1850 },
  },
  {
    id: '002',
    image: 'Images/2.jpg',
    company: 'DenimCo',
    item_name: 'Slim Fit Blue Jeans',
    original_price: 2199,
    current_price: 1399,
    discount_percentage: 36,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.2, count: 1320 },
  },
  {
    id: '003',
    image: 'Images/jacket4.webp',
    company: 'WinterX',
    item_name: 'Men Winter Jacket',
    original_price: 2999,
    current_price: 1699,
    discount_percentage: 38,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.5, count: 980 },
  },

  {
    id: '004',
    image: 'Images/4.webp',
    company: 'Bitya By Bhama',
    item_name: 'Bitya by Bhama Girls yellow & red printed grown Dress',
    original_price: 41900,
    current_price: 1099,
    discount_percentage: 74,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.5, count: 950},
  },

  {
    id: '005',
    image: 'Images/kurta.webp',
    company: 'EthinStyle',
    item_name: 'Women Pritned Kurti',
    original_price: 1799,
    current_price: 1099,
    discount_percentage: 39,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.4, count: 2140},
  },

  {
    id: '006',
    image: 'Images/maxi4.webp',
    company: 'GlowFashion',
    item_name: 'Women Floral Maxi Dress',
    original_price: 2499,
    current_price: 1599,
    discount_percentage: 36,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.5, count: 1680 },
  },
  {
    id: '007',
    image: 'Images/saree7.webp',
    company: 'EthniStyle',
    item_name: 'Red Silk Party Saree',
    original_price: 3999,
    current_price: 2499,
    discount_percentage: 38,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.5, count: 860 },
  },
  {
    id: '008',
    image: 'Images/14.jpg',
    company: 'GlowUp',
    item_name: 'Women Makeup Kit',
    original_price: 3499,
    current_price: 2199,
    discount_percentage: 37,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.3, count: 1250 },
  },
   
  {
    id: '009',
    image: 'Images/shoes2.png',
    company: 'UrbanStep',
    item_name: 'Men Casual Sneakers',
    original_price: 2899,
    current_price: 1799,
    discount_percentage: 38,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.3, count: 1120 },
  },

  {
    id: '010',
    image: 'Images/heel2.png',
    company: 'StyleWalk',
    item_name: 'Women High Heels Stilettos',
    original_price: 3299,
    current_price: 2099,
    discount_percentage: 36,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.4, count: 840 },
  },

  
  {
    id: '011',
    image: 'Images/slipper.png',
    company: 'ComfortWalk',
    item_name: 'Men Causual Rubber Slippers',
    original_price: 999,
    current_price: 599,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.2, count: 820 },
  },

  
  {
    id: '012',
    image: 'Images/wslip.png',
    company: 'UrbanChic',
    item_name: 'Women Stylish Flat Slippers',
    original_price: 1299,
    current_price: 799,
    discount_percentage: 38,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.3, count: 640 },
  },

   {
    id: '013',
    image: 'Images/glass.webp',
    company: 'SunX',
    item_name: 'UV Protected Sunglasses',
    original_price: 1599,
    current_price: 999,
    discount_percentage: 38,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.0, count: 540 },
  },

  {
    id: '014',
    image: 'Images/wallet.png',
    company: 'LeatherPro',
    item_name: 'Genuine Leather Wallet',
    original_price: 1299,
    current_price: 799,
    discount_percentage: 38,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.1, count: 670 },
  },
  {
    id: '015',
    image: 'Images/bottle.png',
    company: 'HydroSteel',
    item_name: 'Stainless Steel Water Bottle',
    original_price: 999,
    current_price: 599,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.6, count: 1680 },
  },
  {
    id: '016',
    image: 'Images/perfume.png',
    company: 'AromaPlus',
    item_name: 'Long Lasting Perfume',
    original_price: 1999,
    current_price: 1299,
    discount_percentage: 35,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.4, count: 880 },
  },
  {
    id: '017',
    image: 'Images/smart1.png',
    company: 'FlitLife',
    item_name: 'Smart Watch with Heart Rate',
    original_price: 4999,
    current_price: 2999,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.2, count: 1950 },
  },

  {
    id: '018',
    image: 'Images/power.png',
    company: 'chargeUp',
    item_name: '10000mAh Power Bank',
    original_price: 1999,
    current_price: 1199,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.3, count: 2200 },
  },
  {
    id: '019',
    image: 'Images/earbuds.png',
    company: 'BeatPro',
    item_name: 'True Wireless Earbuds',
    original_price: 2999,
    current_price: 1699,
    discount_percentage: 43,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.3, count: 3100 },
  },
  {
    id: '020',
    image: 'Images/lap1.png',
    company: 'TechCore',
    item_name: 'Laptop 15.6 inch i5',
    original_price: 59999,
    current_price: 49999,
    discount_percentage: 17,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.5, count: 860 },
  },
   {
    id: '021',
    image: 'Images/car1.png',
    company: 'KiddoFun',
    item_name: 'Kids Remote Control Car',
    original_price: 1999,
    current_price: 1299,
    discount_percentage: 35,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.6, count: 1850 },
  },
   {
    id: '022',
    image: 'Images/toy1.png',
    company: 'TinyJoy',
    item_name: 'Kids Doll House Play Set',
    original_price: 2499,
    current_price: 1599,
    discount_percentage: 36,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.5, count: 1420 },
  },
   {
    id: '023',
    image: 'Images/blok1.png',
    company: 'EduPlay',
    item_name: 'Kids Educational Building Blocks',
    original_price: 1499,
    current_price: 899,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.7, count: 2100 },
  },
   {
    id: '024',
    image: 'Images/teddy.png',
    company: 'CuddleBear',
    item_name: 'Kids Soft Teddy Bear Toy',
    original_price: 1299,
    current_price: 799,
    discount_percentage: 38,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.8, count: 2650 },
  },

  {
    id: '025',
    image: 'Images/kidbag.png',
    company: 'SchoolMate',
    item_name: 'Kids Cartoon School Backpack',
    original_price: 1499,
    current_price: 899,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.6, count: 1280 },
  }
  
];

 const men_Items = [
     {
    id: 'M1',
    image: '/Images/1.webp',
    company: 'StyleHub',
    item_name: 'Men Cotton Printed T-Shirt',
    original_price: 999,
    current_price: 599,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.3, count: 1850 },
  },
   {
    id: 'M2',
    image: '/Images/m2.png',
    company: 'EliteForm',
    item_name: 'Men Premium Formal Blazer',
    original_price: 8999,
    current_price: 5499,
    discount_percentage: 39,
    return_period: 7,
    delivery_date: '5 Jan 2026',
    rating: { stars: 4.5, count: 620 },
  },
    {
    id: 'M3',
    image: '/Images/m3.jpg',
    company: 'StreetCore',
    item_name: 'Men Street Style Cargo Pants',
    original_price: 2999,
    current_price: 1799,
    discount_percentage: 40,
    return_period: 10,
    delivery_date: '4 Jan 2026',
    rating: { stars: 4.7, count: 1980 },
  },
  {
    id: 'M4',
    image: '/Images/m4.jpg',
    company: 'EliteWear',
    item_name: 'Men Tailored Formal Trousers',
    original_price: 2999,
    current_price: 1799,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '1 Jan 2026',
    rating: { stars: 4.4, count: 1180 },
  },
   {
    id: 'M5',
    image: '/Images/m5.jpg',
    company: 'NOIRÉ',
    item_name: 'Men Minimal Tailored Shirt',
    original_price: 3499,
    current_price: 2199,
    discount_percentage: 37,
    return_period: 10,
    delivery_date: '4 Jan 2026',
    rating: { stars: 4.8, count: 520 },
  },
   {
    id: 'M6',
    image: '/Images/m6.jpg',
    company: 'ÉLAN MODE',
    item_name: 'Men Structured Overshirt',
    original_price: 4999,
    current_price: 3199,
    discount_percentage: 36,
    return_period: 7,
    delivery_date: '5 Jan 2026',
    rating: { stars: 4.7, count: 410 },
  },
   {
    id: 'M7',
    image: '/Images/m7.jpg',
    company: 'ATELIER 27',
    item_name: 'Men Textured Knit Polo',
    original_price: 4299,
    current_price: 2699,
    discount_percentage: 37,
    return_period: 10,
    delivery_date: '3 Jan 2026',
    rating: { stars: 4.6, count: 690 },
  },
  {
    id: 'M8',
    image: '/Images/m81.webp',
    company: 'FORME',
    item_name: 'Men Relaxed Tailored Trousers',
    original_price: 5999,
    current_price: 3799,
    discount_percentage: 37,
    return_period: 14,
    delivery_date: '6 Jan 2026',
    rating: { stars: 4.7, count: 340 },
  },
  {
    id: 'M9',
    image: '/Images/m11.webp',
    company: 'Vastra & Co',
    item_name: 'Men Contemporary Ethnic Set',
    original_price: 6999,
    current_price: 4199,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '4 Jan 2026',
    rating: { stars: 4.5, count: 510 },
  },

  {
    id: 'M10',
    image: '/Images/m10.webp',
    company: 'StreetÉlite',
    item_name: 'Men Layered Urban Hoodie',
    original_price: 4999,
    current_price: 2999,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '3 Jan 2026',
    rating: { stars: 4.9, count: 610 },
  },
  {
    id: 'M11',
    image: '/Images/m111.webp',
    company: 'Bata',
    item_name: 'Oxford Formal shoes',
    original_price: 6999,
    current_price: 4199,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '4 Jan 2026',
    rating: { stars: 4.5, count: 510 },
  },
   {
    id: 'M12',
    image: '/Images/shoes2.png',
    company: 'UrbanStep',
    item_name: 'Men Casual Sneakers',
    original_price: 2899,
    current_price: 1799,
    discount_percentage: 14,
    return_period: 14,
    delivery_date: '3 Jan 2026',
    rating: { stars: 4.6, count: 620 },
  },
  {
    id: 'M13',
    image: '/Images/m13.png',
    company: 'Sparx',
    item_name: 'Sparx Men Comfortable Slippers',
    original_price: 599,
    current_price: 399,
    discount_percentage: 33,
    return_period: 7,
    delivery_date: '5 Jan 2026',
    rating: { stars: 4.2, count: 1120 },
  },
   {
    id: 'M14',
    image: '/Images/m14.png',
    company: 'Nike',
    item_name: 'Nike Men Soft Comfort Slippers',
    original_price: 1599,
    current_price: 1199,
    discount_percentage: 25,
    return_period: 10,
    delivery_date: '6 Jan 2026',
    rating: { stars: 4.5, count: 760 },
  },
   {
    id: 'M15',
    image: '/Images/m15.png',
    company: 'Reebok',
    item_name: 'Men Lightweight Sporty Sandals',
    original_price: 1299,
    current_price: 899,
    discount_percentage: 31,
    return_period: 14,
    delivery_date: '4 Jan 2026',
    rating: { stars: 4.3, count: 430 },
  },
]

const women_Items = [
  {
    id: 'w1',
    image: 'Images/maxi4.webp',
    company: 'GlowFashion',
    item_name: 'Women Floral Maxi Dress',
    original_price: 2499,
    current_price: 1599,
    discount_percentage: 36,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.5, count: 1680 },
  },
  {
    id: 'w2',
    image: 'Images/kurta.webp',
    company: 'EthinStyle',
    item_name: 'Women Pritned Kurti',
    original_price: 1799,
    current_price: 1099,
    discount_percentage: 39,
    return_period: 14,
    delivery_date: '31 Dec 2025',
    rating: { stars: 4.4, count: 2140},
  },
  {
    id: 'W3',
    image: 'Images/w3.png',
    company: 'Luna',
    item_name: 'Women Satin Wrap Dress',
    original_price: 4299,
    current_price: 2599,
    discount_percentage: 39,
    return_period: 14,
    delivery_date: '4 Jan 2026',
    rating: { stars: 4.8, count: 740 },
  },
    {
    id: 'W4',
    image: 'Images/w4.png',
    company: 'Breeze',
    item_name: 'Women Flowy Summer Top',
    original_price: 1799,
    current_price: 999,
    discount_percentage: 44,
    return_period: 14,
    delivery_date: '2 Jan 2026',
    rating: { stars: 4.4, count: 1370 },
  },
    {
    id: 'W007',
    image: 'Images/w5.png',
    company: 'DenimAura',
    item_name: 'Women Cropped Denim Jacket',
    original_price: 4499,
    current_price: 2699,
    discount_percentage: 40,
    return_period: 10,
    delivery_date: '6 Jan 2026',
    rating: { stars: 4.6, count: 890 },
  },
  {
    id: 'W6',
    image: 'Images/w6.png',
    company: 'Ethniq',
    item_name: 'Designer Georgette Saree',
    original_price: 8999,
    current_price: 5499,
    discount_percentage: 39,
    return_period: 7,
    delivery_date: '4 Jan 2026',
    rating: { stars: 4.8, count: 410 },
  },
  {
    id: 'W7',
    image: 'Images/w7.jpg',
    company: 'Vastra Heritage',
    item_name: 'Banarasi Silk Saree',
    original_price: 15999,
    current_price: 9999,
    discount_percentage: 38,
    return_period: 7,
    delivery_date: '5 Jan 2026',
    rating: { stars: 4.9, count: 260 },
  },
  {
    id: 'W8',
    image: 'Images/w8.webp',
    company: 'GraceWear',
    item_name: 'Festive Silk Blend Saree',
    original_price: 5999,
    current_price: 3599,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '6 Jan 2026',
    rating: { stars: 4.6, count: 560 },
  },
   {
    id: 'W9',
    image: 'Images/w9.webp',
    company: 'Aura Loom',
    item_name: 'Grey Linen Printed Saree',
    original_price: 3999,
    current_price: 2399,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '3 Jan 2026',
    rating: { stars: 4.5, count: 980 },
  },
  {
    id: 'W10',
    image: 'Images/w10.webp',
    company: 'GlamAura',
    item_name: 'Elegant Black Embroidered Net Saree',
    original_price: 15999,
    current_price: 9999,
    discount_percentage: 38,
    return_period: 7,
    delivery_date: '6 Jan 2026',
    rating: { stars: 4.9, count: 180 },
  },
  {
    id: 'W11',
    image: 'Images/w11.jpg',
    company: 'Chroma',
    item_name: 'Black Ruched Mini Dress',
    original_price: 6499,
    current_price: 3899,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '6 Jan 2026',
    rating: { stars: 4.7, count: 880 },
  },
  {
    id: 'W12',
    image: 'Images/w12.webp',
    company: 'AuraLuxe',
    item_name: 'One-Shoulder Satin Party Dress',
    original_price: 8999,
    current_price: 5399,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '6 Jan 2026',
    rating: { stars: 4.9, count: 420 },
  },
  {
    id: 'W13',
    image: 'Images/w13.webp',
    company: 'Noir Edit',
    item_name: 'Satin Slip Dress with Cowl Neck',
    original_price: 4999,
    current_price: 2999,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '4 Jan 2026',
    rating: { stars: 4.8, count: 980 },
  },
    {
    id: 'W14',
    image: 'Images/w14.webp',
    company: 'Velour Noir',
    item_name: 'Shaded Indo Western Drape Gown',
    original_price: 12999,
    current_price: 7799,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '11 Jan 2026',
    rating: { stars: 4.9, count: 260 },
  },
   {
    id: 'w15',
    image: 'Images/w15.webp',
    company: 'ChicAlchemy',
    item_name: 'Women Mini Bodycon Dress',
    original_price: 8999,
    current_price: 5399,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '11 Jan 2026',
    rating: { stars: 4.9, count: 270 },
  },
]

const footwear_Items = [
  {
    id: "F1",
    image: "Images/f1.webp",
    company: "UrbanStep",
    item_name: "Leather Sneakers",
    rating: { stars: 4.6, count: 320 },
    original_price: 3999,
    current_price: 2499,
    discount_percentage: 38,
    return_period: 14,
    delivery_date: '15 Jan 2026',
  },
  {
    id: "F2",
    image: "Images/f2.webp",
    company: "RunX",
    item_name: "Running Shoes",
    rating: { stars: 4.5, count: 280 },
    original_price: 4999,
    current_price: 3299,
    discount_percentage: 34,
    return_period: 14,
    delivery_date: '15 Jan 2026',
  },
  {
    id: "F3",
    image: "Images/f3.webp",
    company: "StepEase",
    item_name: "Red Chief Formal Derby Shoes",
    rating: { stars: 4.7, count: 190 },
    original_price: 5999,
    current_price: 3899,
    discount_percentage: 35,
    return_period: 14,
    delivery_date: '15 Jan 2026',

  },
   {
    id: "F4",
    image: "Images/f4.webp",
    company: "ComfyWalk",
    item_name: "Cushion Loafers",
    rating: { stars: 4.4, count: 210 },
    original_price: 3499,
    current_price: 2199,
    discount_percentage: 37,
    return_period: 14,
    delivery_date: '15 Jan 2026',
  },
  {
    id: "F5",
    image: "Images/f5.webp",
    company: "RunX",
    item_name: "High-Top Sports Shoes",
    rating: { stars: 4.6, count: 220 },
    original_price: 4599,
    current_price: 2999,
    discount_percentage: 35,
    return_period: 14,
    delivery_date: '15 Jan 2026',
  },
  {
    id: "F6",
    image: "Images/f6.webp",
    company: "StepEase",
    item_name: "Leather Sandals",
    rating: { stars: 4.5, count: 180 },
    original_price: 2499,
    current_price: 1599,
    discount_percentage: 36,
    return_period: 14,
    delivery_date: '15 Jan 2026',
  },
   {
    id: "F7",
    image: "Images/f7.webp",
    company: "ComfyWalk",
    item_name: "Beach Flip-Flops",
    rating: { stars: 4.3, count: 300 },
    original_price: 899,
    current_price: 499,
    discount_percentage: 44,
    return_period: 14,
    delivery_date: '15 Jan 2026',
  },
    {
    id: "F8",
    image: "Images/f8.png",
    company: "ComfyStep",
    item_name: "Cushioned Indoor Slippers",
    rating: { stars: 4.6, count: 160 },
    original_price: 899,
    current_price: 499,
    discount_percentage: 44,
    return_period: 14,
    delivery_date: '15 Jan 2026',
  },
   {
    id: "F9",
    image: "Images/f9.webp",
    company: "SparXStep",
    item_name: "Sporty Strap Sandals",
    rating: { stars: 4.6, count: 170 },
    original_price: 1999,
    current_price: 1299,
    discount_percentage: 35,
    return_period: 14,
    delivery_date: '15 Jan 2026',
  },
  
    {
    id: 'F10',
    image: 'Images/f10.png',
    company: 'StreetFlex',
    item_name: 'Men Printed EVA Fashion Slides',
    original_price: 1799,
    current_price: 1079,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '10 Jan 2026',
    rating: { stars: 4.5, count: 1840 },
  },
  {
    id: 'F11',
    image: 'Images/f11.png',
    company: 'LunaWalk',
    item_name: 'Cushioned Fashion Slippers',
    original_price: 1999,
    current_price: 1199,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '12 Jan 2026',
    rating: { stars: 4.6, count: 2450 },
  },
  {
    id: 'F12',
    image: 'Images/f12.png',
    company: 'UrbanChic',
    item_name: 'Cross Strap Platform Sandals',
    original_price: 3499,
    current_price: 2099,
    discount_percentage: 40,
    return_period: 10,
    delivery_date: '12 Jan 2026',
    rating: { stars: 4.7, count: 1380 },
  },
   {
    id: 'F13',
    image: 'Images/f13.png',
    company: 'Élan Steps',
    item_name: 'Block Heel Party Sandals',
    original_price: 4999,
    current_price: 2999,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '13 Jan 2026',
    rating: { stars: 4.8, count: 920 },
  },
  {
    id: 'F14',
    image: 'Images/f14.png',
    company: 'SilkStep',
    item_name: 'Women Embellished Ethnic Sandals',
    original_price: 3999,
    current_price: 2399,
    discount_percentage: 40,
    return_period: 10,
    delivery_date: '12 Jan 2026',
    rating: { stars: 4.7, count: 1260 },
  },
   {
    id: 'F15',
    image: 'Images/f15.png',
    company: 'UrbanEase',
    item_name: 'Women Flat Mule Slippers',
    original_price: 2499,
    current_price: 1499,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '12 Jan 2026',
    rating: { stars: 4.6, count: 1870 },
  },
  {
    id: 'F16',
    image: 'Images/f16.webp',
    company: 'UrbanChic',
    item_name: 'Chunky Sole Fashion Sneakers',
    original_price: 6999,
    current_price: 4199,
    discount_percentage: 40,
    return_period: 10,
    delivery_date: '14 Jan 2026',
    rating: { stars: 4.8, count: 1850 },
  },
  {
    id: 'F17',
    image: 'Images/f17.webp',
    company: 'LunaWalk',
    item_name: 'Women Lunar Walking Shoes',
    original_price: 5999,
    current_price: 3599,
    discount_percentage: 40,
    return_period: 10,
    delivery_date: '13 Jan 2026',
    rating: { stars: 4.7, count: 2650 },
  },
  {
    id: 'F18',
    image: 'Images/f18.webp',
    company: 'NoirStep',
    item_name: 'Women Pointed Toe Block Heel Pumps',
    original_price: 7499,
    current_price: 4499,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '14 Jan 2026',
    rating: { stars: 4.9, count: 920 },
  },
  {
    id: 'F19',
    image: 'Images/f19.webp',
    company: 'UrbanEase',
    item_name: 'Women Platform Slip-On Sneakers',
    original_price: 6599,
    current_price: 3959,
    discount_percentage: 40,
    return_period: 10,
    delivery_date: '13 Jan 2026',
    rating: { stars: 4.8, count: 1240 },
  },
   {
    id: 'F20',
    image: 'Images/f20.webp',
    company: 'GlowStep',
    item_name: 'Causual Slip-On Sneakers',
    original_price: 5999,
    current_price: 3599,
    discount_percentage: 40,
    return_period: 10,
    delivery_date: '15 Jan 2026',
    rating: { stars: 4.7, count: 1240 },
  },

]

const beauty_Items = [
 {
    id: 'B1',
    image: 'Images/b1.webp',
    company: 'GlowMuse',
    item_name: 'Vanity Wagon Minimalist Face Serum',
    original_price: 1499,
    current_price: 899,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '15 Jan 2026',
    rating: { stars: 4.8, count: 1240 },
  },
  {
    id: 'B2',
    image: 'Images/b21.jpg',
    company: 'AuraLuxe',
    item_name: 'Matte Liquid Lipstick',
    original_price: 999,
    current_price: 599,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '16 Jan 2026',
    rating: { stars: 4.9, count: 950 },
  },
  {
    id: 'B3',
    image: 'Images/b3.png',
    company: 'PureGlow',
    item_name: 'Rose Water Hydrating Toner',
    original_price: 999,
    current_price: 599,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '18 Jan 2026',
    rating: { stars: 4.8, count: 1420 },
  },
  {
    id: 'B4',
    image: 'Images/b4.png',
    company: 'LumiCare',
    item_name: 'Vitamin E Nourishing Face Cream',
    original_price: 1299,
    current_price: 779,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '18 Jan 2026',
    rating: { stars: 4.7, count: 980 },
  },
  {
    id: 'B5',
    image: 'Images/b5.png',
    company: 'AuraSkin',
    item_name: 'Charcoal Deep Clean Face Wash',
    original_price: 899,
    current_price: 539,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '18 Jan 2026',
    rating: { stars: 4.8, count: 1320 },
  },
  {
    id: 'B6',
    image: 'Images/b6.png',
    company: 'SoftGlow',
    item_name: 'Shea Butter Body Lotion',
    original_price: 1199,
    current_price: 719,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '20 Jan 2026',
    rating: { stars: 4.7, count: 1920 },
  },
  {
    id: 'B7',
    image: 'Images/b7.png',
    company: 'SilkTone',
    item_name: 'Cream Blush Palette',
    original_price: 1499,
    current_price: 899,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '20 Jan 2026',
    rating: { stars: 4.9, count: 740 },
  },
  {
    id: 'B8',
    image: 'Images/b8.png',
    company: 'NailAura',
    item_name: 'Gel Finish Nail Polish Set',
    original_price: 1299,
    current_price: 779,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '20 Jan 2026',
    rating: { stars: 4.8, count: 880 },
  },
  {
    id: 'B9',
    image: 'Images/b9.jpg',
    company: 'GlowNest',
    item_name: 'Coffee Infused Under Eye Cream',
    original_price: 1299,
    current_price: 779,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '20 Jan 2026',
    rating: { stars: 4.8, count: 860 },
  },
  {
    id: 'B10',
    image: 'Images/b10.webp',
    company: 'HairLuxe',
    item_name: 'Keratin Smooth Hair Serum',
    original_price: 1399,
    current_price: 839,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '20 Jan 2026',
    rating: { stars: 4.9, count: 1560 },
  },

   {
    id: 'B11',
    image: 'Images/b11.webp',
    company: 'ManCraft',
    item_name: 'Beard Growth Serum',
    original_price: 1499,
    current_price: 899,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '18 Jan 2026',
    rating: { stars: 4.8, count: 860 },
  },
  {
    id: 'B12',
    image: 'Images/b12.jpg',
    company: 'Man Matters',
    item_name: 'Anti Hair Fall Blocking Shampoo',
    original_price: 999,
    current_price: 599,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '18 Jan 2026',
    rating: { stars: 4.7, count: 1340 },
  },
  {
    id: 'B13',
    image: 'Images/b13.jpg',
    company: 'NeoSkin',
    item_name: 'Multani Sunscreen SPF 50',
    original_price: 1299,
    current_price: 779,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '20 Jan 2026',
    rating: { stars: 4.8, count: 770 },
  },
  {
    id: 'B14',
    image: 'Images/b14.jpg',
    company: 'Matte Wax',
    item_name: 'Hair Styling Clay',
    original_price: 799,
    current_price: 479,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '20 Jan 2026',
    rating: { stars: 4.7, count: 910 },
  },
  {
    id: 'B15',
    image: 'Images/b15.webp',
    company: 'UrbanMan',
    item_name: 'Charcoal Face Wash',
    original_price: 899,
    current_price: 539,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '20 Jan 2026',
    rating: { stars: 4.8, count: 1020 },
  },
  {
    id: 'B16',
    image: 'Images/b16.webp',
    company: 'UrbanStyle',
    item_name: 'Women Designer Sunglasses',
    original_price: 2499,
    current_price: 1499,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '16 Jan 2026',
    rating: { stars: 4.8, count: 620 },
  },
  {
    id: 'B17',
    image: 'Images/b17.webp',
    company: 'LuxeEdge',
    item_name: 'Women Fashion Handbag',
    original_price: 4999,
    current_price: 2999,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '16 Jan 2026',
    rating: { stars: 4.8, count: 510 },
  },
   {
    id: 'B18',
    image: 'Images/b18.webp',
    company: 'GlamNest',
    item_name: 'Pearl Drop Earrings',
    original_price: 1999,
    current_price: 1199,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '21 Jan 2026',
    rating: { stars: 4.9, count: 580 },
  },
   {
    id: 'B19',
    image: 'Images/b19.avif',
    company: 'GlowCharm',
    item_name: 'Minimal Pendant Necklace',
    original_price: 2499,
    current_price: 1499,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '21 Jan 2026',
    rating: { stars: 4.9, count: 460 },
  },
  {
    id: 'B20',
    image: 'Images/b20.jpg',
    company: 'ChicNest',
    item_name: 'Beaded Bracelet Set',
    original_price: 1299,
    current_price: 779,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '22 Jan 2026',
    rating: { stars: 4.7, count: 500 },
  },
  {
    id: 'B21',
    image: 'Images/b22.webp',
    company: 'TimeX',
    item_name: 'Men Stainless Steel Watch',
    original_price: 8999,
    current_price: 5399,
    discount_percentage: 40,
    return_period: 7,
    delivery_date: '18 Jan 2026',
    rating: { stars: 4.9, count: 410 },
  },
  {
    id: 'B23',
    image: 'Images/b23.webp',
    company: 'StreetNomad',
    item_name: 'Genuine Leather Crossbody Bag',
    original_price: 3899,
    current_price: 2399,
    discount_percentage: 38,
    return_period: 10,
    delivery_date: '13 Jan 2026',
    rating: { stars: 4.6, count: 520 },
  },
   {
    id: 'B24',
    image: 'Images/b24.webp',
    company: 'EdgeFit',
    item_name: 'Roadster Men\'s Braided Belt',
    original_price: 2999,
    current_price: 1799,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '30 Jan 2026',
    rating: { stars: 4.7, count: 650 },
  },
  {
    id: '25',
    image: 'Images/b25.webp',
    company: 'MonoShade',
    item_name: 'Carlton Lens Rectangle Sunglass',
    original_price: 3799,
    current_price: 2299,
    discount_percentage: 39,
    return_period: 7,
    delivery_date: '18 Feb 2026',
    rating: { stars: 4.6, count: 880 },
  },
  {
    id: 'B26',
    image: 'Images/b26.webp',
    company: 'VaultEdge',
    item_name: 'Bracevor Slim Card Wallet',
    original_price: 3499,
    current_price: 2099,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '19 Feb 2026',
    rating: { stars: 4.7, count: 740 },
  },
]

const electronics_Items = [
 {
  id: 'E1',
  image: 'Images/e1.png',
  company: 'SoundPulse',
  item_name: 'True Wireless Earbuds Pro',
  original_price: 5999,
  current_price: 3999,
  discount_percentage: 33,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.5, count: 1560 },
},
{
  id: 'E2',
  image: 'Images/e2.webp',
  company: 'boAt',
  item_name: 'boAt Bluetooth Headphones',
  original_price: 8999,
  current_price: 5999,
  discount_percentage: 33,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.6, count: 1240 },
},
{
  id: 'E3',
  image: 'Images/e3.jpg',
  company: 'boAt',
  item_name: 'Portable Bluetooth Speaker',
  original_price: 4999,
  current_price: 3299,
  discount_percentage: 34,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.5, count: 1350 },
},
{
  id: 'E4',
  image: 'Images/e4.jpg',
  company: 'TuneUp',
  item_name: 'Neckband Wireless Earphones',
  original_price: 2499,
  current_price: 1599,
  discount_percentage: 36,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.2, count: 890 },
},
{
  id: 'E5',
  image: 'Images/e5.webp',
  company: 'BassLine',
  item_name: 'Over-Ear Wired Headphones',
  original_price: 2999,
  current_price: 1899,
  discount_percentage: 37,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.3, count: 760 },
},
{
  id: 'E6',
  image: 'Images/e6.webp',
  company: 'Noise',
  item_name: 'Smart Fitness Watch',
  original_price: 6999,
  current_price: 4599,
  discount_percentage: 34,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.4, count: 2100 },
},
{
  id: 'E7',
  image: 'Images/e7.webp',
  company: 'FitCore',
  item_name: 'Health Tracking Band',
  original_price: 3499,
  current_price: 2199,
  discount_percentage: 37,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.3, count: 980 },
},
{
  id: 'E8',
  image: 'Images/e8.png',
  company: 'PulseX',
  item_name: 'AMOLED Smartwatch',
  original_price: 8999,
  current_price: 6499,
  discount_percentage: 28,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.6, count: 1240 },
},
{
  id: 'E9',
  image: 'Images/e9.webp',
  company: 'TrackOn',
  item_name: 'Kids GPS Watch',
  original_price: 4999,
  current_price: 1272,
  discount_percentage: 75,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.2, count: 640 },
},
{
  id: 'E10',
  image: 'Images/e10.jpg',
  company: 'Titan',
  item_name: 'Premium Smartwatch Series',
  original_price: 10999,
  current_price: 7999,
  discount_percentage: 27,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.7, count: 530 },
},
{
  id: 'E11',
  image: 'Images/e11.jpg',
  company: 'GameCore',
  item_name: 'Gaming Mouse',
  original_price: 2499,
  current_price: 1599,
  discount_percentage: 36,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.5, count: 980 },
},
{
  id: 'E12',
  image: 'Images/e12.jpg',
  company: 'PlayZone',
  item_name: 'Gaming Headset',
  original_price: 5499,
  current_price: 3799,
  discount_percentage: 31,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.4, count: 860 },
},
{
  id: 'E13',
  image: 'Images/e13.png',
  company: 'GameCore',
  item_name: 'Controller Pad',
  original_price: 3499,
  current_price: 2299,
  discount_percentage: 34,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.3, count: 720 },
},
{
  id: 'E14',
  image: 'Images/e14.webp',
  company: 'VRTech',
  item_name: 'Virtual Reality Headset',
  original_price: 14999,
  current_price: 9999,
  discount_percentage: 33,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.5, count: 410 },
},
{
  id: 'E15',
  image: 'Images/e15.webp',
  company: 'VoltEdge',
  item_name: 'Power Bank 20000mAh',
  original_price: 3499,
  current_price: 2199,
  discount_percentage: 37,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.5, count: 980 },
},
{
  id: 'E16',
  image: 'Images/e16.jpg',
  company: 'DeskEase',
  item_name: 'USB-C Multiport Hub Adapter',
  original_price: 3999,
  current_price: 2699,
  discount_percentage: 33,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.5, count: 1120 },
},
{
  id: 'E17',
  image: 'Images/e17.webp',
  company: 'Urban',
  item_name: 'Smart WiFi Plug',
  original_price: 1999,
  current_price: 1299,
  discount_percentage: 35,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.2, count: 740 },
},
{
  id: 'E18',
  image: 'Images/e18.webp',
  company: 'CamX',
  item_name: 'Smart Security Camera',
  original_price: 4999,
  current_price: 3299,
  discount_percentage: 34,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.5, count: 820 },
},
{
  id: 'E19',
  image: 'Images/e19.webp',
  company: 'AirPure',
  item_name: 'Smart Air Purifier',
  original_price: 6999,
  current_price: 4999,
  discount_percentage: 29,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.3, count: 510 },
},
{
  id: 'E20',
  image: 'Images/e20.webp',
  company: 'Lightify',
  item_name: 'Smart LED Light Bulb',
  original_price: 1499,
  current_price: 999,
  discount_percentage: 33,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.4, count: 920 },
},

]

const kids_Item = [
{
  id: 'K1',
  image: 'Images/k1.webp',
  company: 'CuddleBear',
  item_name: 'Plush Teddy Bear',
  original_price: 1299,
  current_price: 799,
  discount_percentage: 38,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.6, count: 1240 },
},
{
  id: 'K2',
  image: 'Images/k2.jpg',
  company: 'SnuggleToy',
  item_name: 'Soft Bunny Toy',
  original_price: 999,
  current_price: 649,
  discount_percentage: 35,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.5, count: 860 },
},
{
  id: 'K3',
  image: 'Images/k3.webp',
  company: 'FluffyLand',
  item_name: 'Cartoon Character Plush',
  original_price: 1499,
  current_price: 999,
  discount_percentage: 33,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.4, count: 720 },
},
{
  id: 'K4',
  image: 'Images/k4.jpg',
  company: 'SoftHug',
  item_name: 'Kids Pillow Soft Toy',
  original_price: 1799,
  current_price: 1199,
  discount_percentage: 33,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.3, count: 510 },
},
{
  id: 'K5',
  image: 'Images/k5.jpg',
  company: 'HugNest',
  item_name: 'Giant Panda Plush Soft Toy',
  original_price: 1999,
  current_price: 1299,
  discount_percentage: 35,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.7, count: 1580 },
},
{
  id: 'K6',
  image: 'Images/k6.png',
  company: 'Speedy',
  item_name: 'Remote Control Car',
  original_price: 2999,
  current_price: 1999,
  discount_percentage: 33,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.5, count: 980 },
},
{
  id: 'K7',
  image: 'Images/k7.jpg',
  company: 'MiniMotors',
  item_name: 'Realistic Racing Cars',
  original_price: 1499,
  current_price: 999,
  discount_percentage: 33,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.4, count: 760 },
},
{
  id: 'K8',
  image: 'Images/k8.webp',
  company: 'SkyRide',
  item_name: 'Toy Helicopter',
  original_price: 2499,
  current_price: 1699,
  discount_percentage: 32,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.3, count: 430 },
},
{
  id: 'K9',
  image: 'Images/k9.webp',
  company: 'BuildTrack',
  item_name: 'Construction Vehicle Play Set',
  original_price: 1999,
  current_price: 1399,
  discount_percentage: 30,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.4, count: 690 },
},
{
  id: 'K10',
  image: 'Images/k10.png',
  company: 'NeoDrive',
  item_name: 'LED Light Sports Car Toy',
  original_price: 2299,
  current_price: 1499,
  discount_percentage: 35,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.7, count: 1320 },
},
{
  id: 'K11',
  image: 'Images/k11.jpg',
  company: 'BrainyKids',
  item_name: 'Alphabet Learning Board',
  original_price: 999,
  current_price: 649,
  discount_percentage: 35,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.6, count: 890 },
},
{
  id: 'K12',
  image: 'Images/k12.webp',
  company: 'SmartPlay',
  item_name: 'Kids Puzzle Game',
  original_price: 1299,
  current_price: 849,
  discount_percentage: 35,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.5, count: 1040 },
},
{
  id: 'K13',
  image: 'Images/k13.jpg',
  company: 'ThinkGrow',
  item_name: 'Think Fun Math Dice',
  original_price: 1499,
  current_price: 999,
  discount_percentage: 33,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.4, count: 670 },
},
{
  id: 'K14',
  image: 'Images/k14.jpg',
  company: 'EduFun',
  item_name: 'Shape Sorting Cube Toy',
  original_price: 1199,
  current_price: 799,
  discount_percentage: 33,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.5, count: 920 },
},
{
  id: 'K15',
  image: 'Images/k15.webp',
  company: 'LearnFun',
  item_name: 'Pludo STEM Kit Pendulum Play',
  original_price: 2499,
  current_price: 1699,
  discount_percentage: 32,
  return_period: 7,
  delivery_date: '19 Feb 2026',
  rating: { stars: 4.6, count: 890 },
},
]

